packages:
  - packages/*

onlyBuiltDependencies:
  - bcrypt
  - better-sqlite3
  - core-js
  - esbuild
  - sharp
  - sqlite3
  - unrs-resolver
  - yencode

patchedDependencies:
  stremthru: patches/stremthru.patch
  yencode@1.2.4: patches/yencode@1.2.4.patch
